namespace PortiaNet.Helper.MasterData
{
    public class Country : MasterData
    {
        public string? Code { get; set; }

        public string? ISDCode { get; set; } = string.Empty;

        public string? GMT { get; set; } = string.Empty;

        private static List<Country> Countries => new()
        {
            new Country() { Name = "Afghanistan", Code = "AFG", RefNo = "001" },
                new Country() { Name = "Åland Islands", Code = "ALA", RefNo = "002" },
                new Country() { Name = "Albania", Code = "ALB", RefNo = "003" },
                new Country() { Name = "Algeria", Code = "DZA", RefNo = "004" },
                new Country() { Name = "American Samoa", Code = "ASM", RefNo = "005" },
                new Country() { Name = "Andorra", Code = "AND", RefNo = "006" },
                new Country() { Name = "Angola", Code = "AGO", RefNo = "007" },
                new Country() { Name = "Anguilla", Code = "AIA", RefNo = "008" },
                new Country() { Name = "Antarctica", Code = "ATA", RefNo = "009" },
                new Country() { Name = "Antigua and Barbuda", Code = "ATG", RefNo = "010" },
                new Country() { Name = "Argentina", Code = "ARG", RefNo = "011" },
                new Country() { Name = "Armenia", Code = "ARM", RefNo = "012" },
                new Country() { Name = "Aruba", Code = "ABW", RefNo = "013" },
                new Country() { Name = "Australia", Code = "AUS", RefNo = "014" },
                new Country() { Name = "Austria", Code = "AUT", RefNo = "015" },
                new Country() { Name = "Azerbaijan", Code = "AZE", RefNo = "016" },
                new Country() { Name = "Bahamas (the)", Code = "BHS", RefNo = "017" },
                new Country() { Name = "Bahrain", Code = "BHR", RefNo = "018" },
                new Country() { Name = "Bangladesh", Code = "BGD", RefNo = "019" },
                new Country() { Name = "Barbados", Code = "BRB", RefNo = "020" },
                new Country() { Name = "Belarus", Code = "BLR", RefNo = "021" },
                new Country() { Name = "Belgium", Code = "BEL", RefNo = "022" },
                new Country() { Name = "Belize", Code = "BLZ", RefNo = "023" },
                new Country() { Name = "Benin", Code = "BEN", RefNo = "024" },
                new Country() { Name = "Bermuda", Code = "BMU", RefNo = "025" },
                new Country() { Name = "Bhutan", Code = "BTN", RefNo = "026" },
                new Country() { Name = "Bolivia (Plurinational State of)", Code = "BOL", RefNo = "027" },
                new Country() { Name = "Bonaire, Sint Eustatius and Saba", Code = "BES", RefNo = "028" },
                new Country() { Name = "Bosnia and Herzegovina", Code = "BIH", RefNo = "029" },
                new Country() { Name = "Botswana", Code = "BWA", RefNo = "030" },
                new Country() { Name = "Bouvet Island", Code = "BVT", RefNo = "031" },
                new Country() { Name = "Brazil", Code = "BRA", RefNo = "032" },
                new Country() { Name = "British Indian Ocean Territory (the)", Code = "IOT", RefNo = "033" },
                new Country() { Name = "Brunei Darussalam", Code = "BRN", RefNo = "034" },
                new Country() { Name = "Bulgaria", Code = "BGR", RefNo = "035" },
                new Country() { Name = "Burkina Faso", Code = "BFA", RefNo = "036" },
                new Country() { Name = "Burundi", Code = "BDI", RefNo = "037" },
                new Country() { Name = "Cabo Verde", Code = "CPV", RefNo = "038" },
                new Country() { Name = "Cambodia", Code = "KHM", RefNo = "039" },
                new Country() { Name = "Cameroon", Code = "CMR", RefNo = "040" },
                new Country() { Name = "Canada", Code = "CAN", RefNo = "041" },
                new Country() { Name = "Cayman Islands (the)", Code = "CYM", RefNo = "042" },
                new Country() { Name = "Central African Republic (the)", Code = "CAF", RefNo = "043" },
                new Country() { Name = "Chad", Code = "TCD", RefNo = "044" },
                new Country() { Name = "Chile", Code = "CHL", RefNo = "045" },
                new Country() { Name = "China", Code = "CHN", RefNo = "046" },
                new Country() { Name = "Christmas Island", Code = "CXR", RefNo = "047" },
                new Country() { Name = "Cocos (Keeling) Islands (the)", Code = "CCK", RefNo = "048" },
                new Country() { Name = "Colombia", Code = "COL", RefNo = "049" },
                new Country() { Name = "Comoros (the)", Code = "COM", RefNo = "050" },
                new Country() { Name = "Congo (the Democratic Republic of the)", Code = "COD", RefNo = "051" },
                new Country() { Name = "Congo (the)", Code = "COG", RefNo = "052" },
                new Country() { Name = "Cook Islands (the)", Code = "COK", RefNo = "053"},
                new Country() { Name = "Costa Rica", Code = "CRI", RefNo = "054"},
                new Country() { Name = "Côte d'Ivoire", Code = "CIV", RefNo = "055"},
                new Country() { Name = "Croatia", Code = "HRV", RefNo = "056"},
                new Country() { Name = "Cuba", Code = "CUB", RefNo = "057"},
                new Country() { Name = "Curaçao", Code = "CUW", RefNo = "058"},
                new Country() { Name = "Cyprus", Code = "CYP", RefNo = "059"},
                new Country() { Name = "Czechia", Code = "CZE", RefNo = "060"},
                new Country() { Name = "Denmark", Code = "DNK", RefNo = "061"},
                new Country() { Name = "Djibouti", Code = "DJI", RefNo = "062"},
                new Country() { Name = "Dominica", Code = "DMA", RefNo = "063"},
                new Country() { Name = "Dominican Republic (the)", Code = "DOM", RefNo = "064"},
                new Country() { Name = "Ecuador", Code = "ECU", RefNo = "065"},
                new Country() { Name = "Egypt", Code = "EGY", RefNo = "066"},
                new Country() { Name = "El Salvador", Code = "SLV", RefNo = "067"},
                new Country() { Name = "Equatorial Guinea", Code = "GNQ", RefNo = "068"},
                new Country() { Name = "Eritrea", Code = "ERI", RefNo = "069"},
                new Country() { Name = "Estonia", Code = "EST", RefNo = "070"},
                new Country() { Name = "Eswatini", Code = "SWZ", RefNo = "071"},
                new Country() { Name = "Ethiopia", Code = "ETH", RefNo = "072"},
                new Country() { Name = "Falkland Islands (the) [Malvinas]", Code = "FLK", RefNo = "073"},
                new Country() { Name = "Faroe Islands (the)", Code = "FRO", RefNo = "074"},
                new Country() { Name = "Fiji", Code = "FJI", RefNo = "075"},
                new Country() { Name = "Finland", Code = "FIN", RefNo = "076"},
                new Country() { Name = "France", Code = "FRA", RefNo = "077"},
                new Country() { Name = "French Guiana", Code = "GUF", RefNo = "078"},
                new Country() { Name = "French Polynesia", Code = "PYF", RefNo = "079"},
                new Country() { Name = "French Southern Territories (the)", Code = "ATF", RefNo = "080"},
                new Country() { Name = "Gabon", Code = "GAB", RefNo = "081"},
                new Country() { Name = "Gambia (the)", Code = "GMB", RefNo = "082"},
                new Country() { Name = "Georgia", Code = "GEO", RefNo = "083"},
                new Country() { Name = "Germany", Code = "DEU", RefNo = "084"},
                new Country() { Name = "Ghana", Code = "GHA", RefNo = "085"},
                new Country() { Name = "Gibraltar", Code = "GIB", RefNo = "086"},
                new Country() { Name = "Greece", Code = "GRC", RefNo = "087"},
                new Country() { Name = "Greenland", Code = "GRL", RefNo = "088"},
                new Country() { Name = "Grenada", Code = "GRD", RefNo = "089"},
                new Country() { Name = "Guadeloupe", Code = "GLP", RefNo = "090"},
                new Country() { Name = "Guam", Code = "GUM", RefNo = "091"},
                new Country() { Name = "Guatemala", Code = "GTM", RefNo = "092"},
                new Country() { Name = "Guernsey", Code = "GGY", RefNo = "093"},
                new Country() { Name = "Guinea", Code = "GIN", RefNo = "094"},
                new Country() { Name = "Guinea-Bissau", Code = "GNB", RefNo = "095"},
                new Country() { Name = "Guyana", Code = "GUY", RefNo = "096"},
                new Country() { Name = "Haiti", Code = "HTI", RefNo = "097"},
                new Country() { Name = "Heard Island and McDonald Islands", Code = "HMD", RefNo = "098"},
                new Country() { Name = "Holy See (the)", Code = "VAT", RefNo = "099"},
                new Country() { Name = "Honduras", Code = "HND", RefNo = "100"},
                new Country() { Name = "Hong Kong", Code = "HKG", RefNo = "101"},
                new Country() { Name = "Hungary", Code = "HUN", RefNo = "102"},
                new Country() { Name = "Iceland", Code = "ISL", RefNo = "103"},
                new Country() { Name = "India", Code = "IND", RefNo = "104"},
                new Country() { Name = "Indonesia", Code = "IDN", RefNo = "105"},
                new Country() { Name = "Iran (Islamic Republic of)", Code = "IRN", RefNo = "106"},
                new Country() { Name = "Iraq", Code = "IRQ", RefNo = "107"},
                new Country() { Name = "Ireland", Code = "IRL", RefNo = "108"},
                new Country() { Name = "Isle of Man", Code = "IMN", RefNo = "109"},
                new Country() { Name = "Israel", Code = "ISR", RefNo = "110"},
                new Country() { Name = "Italy", Code = "ITA", RefNo = "111"},
                new Country() { Name = "Jamaica", Code = "JAM", RefNo = "112"},
                new Country() { Name = "Japan", Code = "JPN", RefNo = "113"},
                new Country() { Name = "Jersey", Code = "JEY", RefNo = "114"},
                new Country() { Name = "Jordan", Code = "JOR", RefNo = "115"},
                new Country() { Name = "Kazakhstan", Code = "KAZ", RefNo = "116"},
                new Country() { Name = "Kenya", Code = "KEN", RefNo = "117"},
                new Country() { Name = "Kiribati", Code = "KIR", RefNo = "118"},
                new Country() { Name = "North Korea (the Democratic People's Republic of)", Code = "PRK", RefNo = "119"},
                new Country() { Name = "South Korea (the Republic of)", Code = "KOR", RefNo = "120"},
                new Country() { Name = "Kuwait", Code = "KWT", RefNo = "121"},
                new Country() { Name = "Kyrgyzstan", Code = "KGZ", RefNo = "122"},
                new Country() { Name = "Lao People's Democratic Republic (the)", Code = "LAO", RefNo = "123"},
                new Country() { Name = "Latvia", Code = "LVA", RefNo = "124"},
                new Country() { Name = "Lebanon", Code = "LBN", RefNo = "125"},
                new Country() { Name = "Lesotho", Code = "LSO", RefNo = "126"},
                new Country() { Name = "Liberia", Code = "LBR", RefNo = "127"},
                new Country() { Name = "Libya", Code = "LBY", RefNo = "128"},
                new Country() { Name = "Liechtenstein", Code = "LIE", RefNo = "129"},
                new Country() { Name = "Lithuania", Code = "LTU", RefNo = "130"},
                new Country() { Name = "Luxembourg", Code = "LUX", RefNo = "131"},
                new Country() { Name = "Macao", Code = "MAC", RefNo = "132"},
                new Country() { Name = "Republic of North Macedonia", Code = "MKD", RefNo = "133"},
                new Country() { Name = "Madagascar", Code = "MDG", RefNo = "134"},
                new Country() { Name = "Malawi", Code = "MWI", RefNo = "135"},
                new Country() { Name = "Malaysia", Code = "MYS", RefNo = "136"},
                new Country() { Name = "Maldives", Code = "MDV", RefNo = "137"},
                new Country() { Name = "Mali", Code = "MLI", RefNo = "138"},
                new Country() { Name = "Malta", Code = "MLT", RefNo = "139"},
                new Country() { Name = "Marshall Islands (the)", Code = "MHL", RefNo = "140"},
                new Country() { Name = "Martinique", Code = "MTQ", RefNo = "141"},
                new Country() { Name = "Mauritania", Code = "MRT", RefNo = "142"},
                new Country() { Name = "Mauritius", Code = "MUS", RefNo = "143"},
                new Country() { Name = "Mayotte", Code = "MYT", RefNo = "144"},
                new Country() { Name = "Mexico", Code = "MEX", RefNo = "145"},
                new Country() { Name = "Micronesia (Federated States of)", Code = "FSM", RefNo = "146"},
                new Country() { Name = "Moldova (the Republic of)", Code = "MDA", RefNo = "147"},
                new Country() { Name = "Monaco", Code = "MCO", RefNo = "148"},
                new Country() { Name = "Mongolia", Code = "MNG", RefNo = "149"},
                new Country() { Name = "Montenegro", Code = "MNE", RefNo = "150"},
                new Country() { Name = "Montserrat", Code = "MSR", RefNo = "151"},
                new Country() { Name = "Morocco", Code = "MAR", RefNo = "152"},
                new Country() { Name = "Mozambique", Code = "MOZ", RefNo = "153"},
                new Country() { Name = "Myanmar", Code = "MMR", RefNo = "154"},
                new Country() { Name = "Namibia", Code = "NAM", RefNo = "155"},
                new Country() { Name = "Nauru", Code = "NRU", RefNo = "156"},
                new Country() { Name = "Nepal", Code = "NPL", RefNo = "157"},
                new Country() { Name = "Netherlands (the)", Code = "NLD", RefNo = "158"},
                new Country() { Name = "New Caledonia", Code = "NCL", RefNo = "159"},
                new Country() { Name = "New Zealand", Code = "NZL", RefNo = "160"},
                new Country() { Name = "Nicaragua", Code = "NIC", RefNo = "161"},
                new Country() { Name = "Niger (the)", Code = "NER", RefNo = "162"},
                new Country() { Name = "Nigeria", Code = "NGA", RefNo = "163"},
                new Country() { Name = "Niue", Code = "NIU", RefNo = "164"},
                new Country() { Name = "Norfolk Island", Code = "NFK", RefNo = "165"},
                new Country() { Name = "Northern Mariana Islands (the)", Code = "MNP", RefNo = "166"},
                new Country() { Name = "Norway", Code = "NOR", RefNo = "167"},
                new Country() { Name = "Oman", Code = "OMN", RefNo = "168"},
                new Country() { Name = "Pakistan", Code = "PAK", RefNo = "169"},
                new Country() { Name = "Palau", Code = "PLW", RefNo = "170"},
                new Country() { Name = "Palestine, State of", Code = "PSE", RefNo = "171"},
                new Country() { Name = "Panama", Code = "PAN", RefNo = "172"},
                new Country() { Name = "Papua New Guinea", Code = "PNG", RefNo = "173"},
                new Country() { Name = "Paraguay", Code = "PRY", RefNo = "174"},
                new Country() { Name = "Peru", Code = "PER", RefNo = "175"},
                new Country() { Name = "Philippines (the)", Code = "PHL", RefNo = "176"},
                new Country() { Name = "Pitcairn", Code = "PCN", RefNo = "177"},
                new Country() { Name = "Poland", Code = "POL", RefNo = "178"},
                new Country() { Name = "Portugal", Code = "PRT", RefNo = "179"},
                new Country() { Name = "Puerto Rico", Code = "PRI", RefNo = "180"},
                new Country() { Name = "Qatar", Code = "QAT", RefNo = "181"},
                new Country() { Name = "Réunion", Code = "REU", RefNo = "182"},
                new Country() { Name = "Romania", Code = "ROU", RefNo = "183"},
                new Country() { Name = "Russian Federation (the)", Code = "RUS", RefNo = "184"},
                new Country() { Name = "Rwanda", Code = "RWA", RefNo = "185"},
                new Country() { Name = "Saint Barthélemy", Code = "BLM", RefNo = "186"},
                new Country() { Name = "Saint Helena, Ascension and Tristan da Cunha", Code = "SHN", RefNo = "187"},
                new Country() { Name = "Saint Kitts and Nevis", Code = "KNA", RefNo = "188"},
                new Country() { Name = "Saint Lucia", Code = "LCA", RefNo = "189"},
                new Country() { Name = "Saint Martin (French part)", Code = "MAF", RefNo = "190"},
                new Country() { Name = "Saint Pierre and Miquelon", Code = "SPM", RefNo = "191"},
                new Country() { Name = "Saint Vincent and the Grenadines", Code = "VCT", RefNo = "192"},
                new Country() { Name = "Samoa", Code = "WSM", RefNo = "193"},
                new Country() { Name = "San Marino", Code = "SMR", RefNo = "194"},
                new Country() { Name = "Sao Tome and Principe", Code = "STP", RefNo = "195"},
                new Country() { Name = "Saudi Arabia", Code = "SAU", RefNo = "196"},
                new Country() { Name = "Senegal", Code = "SEN", RefNo = "197"},
                new Country() { Name = "Serbia", Code = "SRB", RefNo = "198"},
                new Country() { Name = "Seychelles", Code = "SYC", RefNo = "199"},
                new Country() { Name = "Sierra Leone", Code = "SLE", RefNo = "200"},
                new Country() { Name = "Singapore", Code = "SGP", RefNo = "201"},
                new Country() { Name = "Sint Maarten (Dutch part)", Code = "SXM", RefNo = "202"},
                new Country() { Name = "Slovakia", Code = "SVK", RefNo = "203"},
                new Country() { Name = "Slovenia", Code = "SVN", RefNo = "204"},
                new Country() { Name = "Solomon Islands", Code = "SLB", RefNo = "205"},
                new Country() { Name = "Somalia", Code = "SOM", RefNo = "206"},
                new Country() { Name = "South Africa", Code = "ZAF", RefNo = "207"},
                new Country() { Name = "South Georgia and the South Sandwich Islands", Code = "SGS", RefNo = "208"},
                new Country() { Name = "South Sudan", Code = "SSD", RefNo = "209"},
                new Country() { Name = "Spain", Code = "ESP", RefNo = "210"},
                new Country() { Name = "Sri Lanka", Code = "LKA", RefNo = "211"},
                new Country() { Name = "Sudan (the)", Code = "SDN", RefNo = "212"},
                new Country() { Name = "Suriname", Code = "SUR", RefNo = "213"},
                new Country() { Name = "Svalbard and Jan Mayen", Code = "SJM", RefNo = "214"},
                new Country() { Name = "Sweden", Code = "SWE", RefNo = "215"},
                new Country() { Name = "Switzerland", Code = "CHE", RefNo = "216"},
                new Country() { Name = "Syrian Arab Republic", Code = "SYR", RefNo = "217"},
                new Country() { Name = "Taiwan (Province of China)", Code = "TWN", RefNo = "218"},
                new Country() { Name = "Tajikistan", Code = "TJK", RefNo = "219"},
                new Country() { Name = "Tanzania, United Republic of", Code = "TZA", RefNo = "220"},
                new Country() { Name = "Thailand", Code = "THA", RefNo = "221"},
                new Country() { Name = "Timor-Leste", Code = "TLS", RefNo = "222"},
                new Country() { Name = "Togo", Code = "TGO", RefNo = "223"},
                new Country() { Name = "Tokelau", Code = "TKL", RefNo = "224"},
                new Country() { Name = "Tonga", Code = "TON", RefNo = "225"},
                new Country() { Name = "Trinidad and Tobago", Code = "TTO", RefNo = "226"},
                new Country() { Name = "Tunisia", Code = "TUN", RefNo = "227"},
                new Country() { Name = "Turkey", Code = "TUR", RefNo = "228"},
                new Country() { Name = "Turkmenistan", Code = "TKM", RefNo = "229"},
                new Country() { Name = "Turks and Caicos Islands (the)", Code = "TCA", RefNo = "230"},
                new Country() { Name = "Tuvalu", Code = "TUV", RefNo = "231"},
                new Country() { Name = "Uganda", Code = "UGA", RefNo = "232"},
                new Country() { Name = "Ukraine", Code = "UKR", RefNo = "233"},
                new Country() { Name = "United Arab Emirates (the)", Code = "ARE", RefNo = "234"},
                new Country() { Name = "United Kingdom of Great Britain", Code = "GBR", RefNo = "235"},
                new Country() { Name = "United States Minor Outlying Islands (the)", Code = "UMI", RefNo = "236"},
                new Country() { Name = "United States of America (the)", Code = "USA", RefNo = "237"},
                new Country() { Name = "Uruguay", Code = "URY", RefNo = "238"},
                new Country() { Name = "Uzbekistan", Code = "UZB", RefNo = "239"},
                new Country() { Name = "Vanuatu", Code = "VUT", RefNo = "240"},
                new Country() { Name = "Venezuela (Bolivarian Republic of)", Code = "VEN", RefNo = "241"},
                new Country() { Name = "Viet Nam", Code = "VNM", RefNo = "242"},
                new Country() { Name = "Virgin Islands (British)", Code = "VGB", RefNo = "243"},
                new Country() { Name = "Virgin Islands (U.S.)", Code = "VIR", RefNo = "244"},
                new Country() { Name = "Wallis and Futuna", Code = "WLF", RefNo = "245"},
                new Country() { Name = "Western Sahara", Code = "ESH", RefNo = "246"},
                new Country() { Name = "Yemen", Code = "YEM", RefNo = "247"},
                new Country() { Name = "Zambia", Code = "ZMB", RefNo = "248"},
                new Country() { Name = "Zimbabwe", Code = "ZWE", RefNo = "249" },
        };

        public static List<Country> GetAll() => Countries;
    }
}
