namespace PortiaNet.Helper.MasterData
{
    public class Country : MasterData
    {
        public string? Code { get; set; }

        public string? ISDCode { get; set; } = string.Empty;

        public string? GMT { get; set; } = string.Empty;

        private static List<Country> Countries => new()
        {
            new Country() { RefNo = "001", Code = "AFG", Name = "Afghanistan" },
            new Country() { RefNo = "002", Code = "ALB", Name = "Albania" },
            new Country() { RefNo = "003", Code = "DZA", Name = "Algeria" },
            new Country() { RefNo = "004", Code = "AND", Name = "Andorra" },
            new Country() { RefNo = "005", Code = "AGO", Name = "Angola" },
            new Country() { RefNo = "006", Code = "ATA", Name = "Antarctica" },
            new Country() { RefNo = "007", Code = "ATG", Name = "Antigua and Barbuda" },
            new Country() { RefNo = "008", Code = "ARG", Name = "Argentina" },
            new Country() { RefNo = "009", Code = "ARM", Name = "Armenia" },
            new Country() { RefNo = "010", Code = "ABW", Name = "Aruba" },
            new Country() { RefNo = "011", Code = "AUS", Name = "Australia" },
            new Country() { RefNo = "012", Code = "AUT", Name = "Austria" },
            new Country() { RefNo = "013", Code = "AZE", Name = "Azerbaijan" },
            new Country() { RefNo = "014", Code = "BHS", Name = "Bahamas" },
            new Country() { RefNo = "015", Code = "BHR", Name = "Bahrain" },
            new Country() { RefNo = "016", Code = "BGD", Name = "Bangladesh" },
            new Country() { RefNo = "017", Code = "BRB", Name = "Barbados" },
            new Country() { RefNo = "018", Code = "BLR", Name = "Belarus" },
            new Country() { RefNo = "019", Code = "BEL", Name = "Belgium" },
            new Country() { RefNo = "020", Code = "BLZ", Name = "Belize" },
            new Country() { RefNo = "021", Code = "BEN", Name = "Benin" },
            new Country() { RefNo = "022", Code = "BMU", Name = "Bermuda" },
            new Country() { RefNo = "023", Code = "BTN", Name = "Bhutan" },
            new Country() { RefNo = "024", Code = "BOL", Name = "Bolivia" },
            new Country() { RefNo = "025", Code = "BIH", Name = "Bosnia and Herzegovina" },
            new Country() { RefNo = "026", Code = "BWA", Name = "Botswana" },
            new Country() { RefNo = "027", Code = "BRA", Name = "Brazil" },
            new Country() { RefNo = "028", Code = "BRN", Name = "Brunei" },
            new Country() { RefNo = "029", Code = "BGR", Name = "Bulgaria" },
            new Country() { RefNo = "030", Code = "BFA", Name = "Burkina Faso" },
            new Country() { RefNo = "031", Code = "BDI", Name = "Burundi" },
            new Country() { RefNo = "032", Code = "KHM", Name = "Cambodia" },
            new Country() { RefNo = "033", Code = "CMR", Name = "Cameroon" },
            new Country() { RefNo = "034", Code = "CAN", Name = "Canada" },
            new Country() { RefNo = "035", Code = "CAF", Name = "Central African Republic" },
            new Country() { RefNo = "036", Code = "TCD", Name = "Chad" },
            new Country() { RefNo = "037", Code = "CHL", Name = "Chile" },
            new Country() { RefNo = "038", Code = "CHN", Name = "China" },
            new Country() { RefNo = "039", Code = "CXR", Name = "Christmas Island" },
            new Country() { RefNo = "040", Code = "COL", Name = "Colombia" },
            new Country() { RefNo = "041", Code = "COM", Name = "Comoros" },
            new Country() { RefNo = "042", Code = "COG", Name = "Congo" },
            new Country() { RefNo = "043", Code = "CRI", Name = "Costa Rica" },
            new Country() { RefNo = "044", Code = "HRV", Name = "Croatia" },
            new Country() { RefNo = "045", Code = "CUB", Name = "Cuba" },
            new Country() { RefNo = "046", Code = "CYP", Name = "Cyprus" },
            new Country() { RefNo = "047", Code = "CZE", Name = "Czechia" },
            new Country() { RefNo = "048", Code = "DNK", Name = "Denmark" },
            new Country() { RefNo = "049", Code = "DJI", Name = "Djibouti" },
            new Country() { RefNo = "050", Code = "DMA", Name = "Dominica" },
            new Country() { RefNo = "051", Code = "DOM", Name = "Dominican Republic" },
            new Country() { RefNo = "052", Code = "ECU", Name = "Ecuador" },
            new Country() { RefNo = "053", Code = "EGY", Name = "Egypt" },
            new Country() { RefNo = "054", Code = "SLV", Name = "El Salvador" },
            new Country() { RefNo = "055", Code = "ERI", Name = "Eritrea" },
            new Country() { RefNo = "056", Code = "EST", Name = "Estonia" },
            new Country() { RefNo = "057", Code = "SWZ", Name = "Eswatini" },
            new Country() { RefNo = "058", Code = "ETH", Name = "Ethiopia" },
            new Country() { RefNo = "059", Code = "FRO", Name = "Faroe Islands" },
            new Country() { RefNo = "060", Code = "FJI", Name = "Fiji" },
            new Country() { RefNo = "061", Code = "FIN", Name = "Finland" },
            new Country() { RefNo = "062", Code = "FRA", Name = "France" },
            new Country() { RefNo = "063", Code = "PYF", Name = "French Polynesia" },
            new Country() { RefNo = "064", Code = "GAB", Name = "Gabon" },
            new Country() { RefNo = "065", Code = "GMB", Name = "Gambia" },
            new Country() { RefNo = "066", Code = "GEO", Name = "Georgia" },
            new Country() { RefNo = "067", Code = "DEU", Name = "Germany" },
            new Country() { RefNo = "068", Code = "GHA", Name = "Ghana" },
            new Country() { RefNo = "069", Code = "GIB", Name = "Gibraltar" },
            new Country() { RefNo = "070", Code = "GRC", Name = "Greece" },
            new Country() { RefNo = "071", Code = "GRL", Name = "Greenland" },
            new Country() { RefNo = "072", Code = "GRD", Name = "Grenada" },
            new Country() { RefNo = "073", Code = "GUM", Name = "Guam" },
            new Country() { RefNo = "074", Code = "GTM", Name = "Guatemala" },
            new Country() { RefNo = "075", Code = "GIN", Name = "Guinea" },
            new Country() { RefNo = "076", Code = "GNB", Name = "Guinea-Bissau" },
            new Country() { RefNo = "077", Code = "GUY", Name = "Guyana" },
            new Country() { RefNo = "078", Code = "HTI", Name = "Haiti" },
            new Country() { RefNo = "079", Code = "HND", Name = "Honduras" },
            new Country() { RefNo = "080", Code = "HKG", Name = "Hong Kong" },
            new Country() { RefNo = "081", Code = "HUN", Name = "Hungary" },
            new Country() { RefNo = "082", Code = "ISL", Name = "Iceland" },
            new Country() { RefNo = "083", Code = "IND", Name = "India" },
            new Country() { RefNo = "084", Code = "IDN", Name = "Indonesia" },
            new Country() { RefNo = "085", Code = "IRN", Name = "Iran" },
            new Country() { RefNo = "086", Code = "IRQ", Name = "Iraq" },
            new Country() { RefNo = "087", Code = "IRL", Name = "Ireland" },
            new Country() { RefNo = "088", Code = "IMN", Name = "Isle of Man" },
            new Country() { RefNo = "089", Code = "ISR", Name = "Israel" },
            new Country() { RefNo = "090", Code = "ITA", Name = "Italy" },
            new Country() { RefNo = "091", Code = "JAM", Name = "Jamaica" },
            new Country() { RefNo = "092", Code = "JPN", Name = "Japan" },
            new Country() { RefNo = "093", Code = "JOR", Name = "Jordan" },
            new Country() { RefNo = "094", Code = "KAZ", Name = "Kazakhstan" },
            new Country() { RefNo = "095", Code = "KEN", Name = "Kenya" },
            new Country() { RefNo = "096", Code = "KIR", Name = "Kiribati" },
            new Country() { RefNo = "097", Code = "KWT", Name = "Kuwait" },
            new Country() { RefNo = "098", Code = "KGZ", Name = "Kyrgyzstan" },
            new Country() { RefNo = "099", Code = "LVA", Name = "Latvia" },
            new Country() { RefNo = "100", Code = "LBN", Name = "Lebanon" },
            new Country() { RefNo = "101", Code = "LSO", Name = "Lesotho" },
            new Country() { RefNo = "102", Code = "LBR", Name = "Liberia" },
            new Country() { RefNo = "103", Code = "LBY", Name = "Libya" },
            new Country() { RefNo = "104", Code = "LIE", Name = "Liechtenstein" },
            new Country() { RefNo = "105", Code = "LTU", Name = "Lithuania" },
            new Country() { RefNo = "106", Code = "LUX", Name = "Luxembourg" },
            new Country() { RefNo = "107", Code = "MAC", Name = "Macao" },
            new Country() { RefNo = "108", Code = "MDG", Name = "Madagascar" },
            new Country() { RefNo = "109", Code = "MWI", Name = "Malawi" },
            new Country() { RefNo = "110", Code = "MYS", Name = "Malaysia" },
            new Country() { RefNo = "111", Code = "MDV", Name = "Maldives" },
            new Country() { RefNo = "112", Code = "MLI", Name = "Mali" },
            new Country() { RefNo = "113", Code = "MLT", Name = "Malta" },
            new Country() { RefNo = "114", Code = "MHL", Name = "Marshall Islands" },
            new Country() { RefNo = "115", Code = "MRT", Name = "Mauritania" },
            new Country() { RefNo = "116", Code = "MUS", Name = "Mauritius" },
            new Country() { RefNo = "117", Code = "MEX", Name = "Mexico" },
            new Country() { RefNo = "118", Code = "FSM", Name = "Micronesia" },
            new Country() { RefNo = "119", Code = "MDA", Name = "Moldova" },
            new Country() { RefNo = "120", Code = "MCO", Name = "Monaco" },
            new Country() { RefNo = "121", Code = "MNG", Name = "Mongolia" },
            new Country() { RefNo = "122", Code = "MNE", Name = "Montenegro" },
            new Country() { RefNo = "123", Code = "MAR", Name = "Morocco" },
            new Country() { RefNo = "124", Code = "MOZ", Name = "Mozambique" },
            new Country() { RefNo = "125", Code = "MMR", Name = "Myanmar" },
            new Country() { RefNo = "126", Code = "NAM", Name = "Namibia" },
            new Country() { RefNo = "127", Code = "NRU", Name = "Nauru" },
            new Country() { RefNo = "128", Code = "NPL", Name = "Nepal" },
            new Country() { RefNo = "129", Code = "NLD", Name = "Netherlands" },
            new Country() { RefNo = "130", Code = "NCL", Name = "New Caledonia" },
            new Country() { RefNo = "131", Code = "NZL", Name = "New Zealand" },
            new Country() { RefNo = "132", Code = "NIC", Name = "Nicaragua" },
            new Country() { RefNo = "133", Code = "NER", Name = "Niger" },
            new Country() { RefNo = "134", Code = "NGA", Name = "Nigeria" },
            new Country() { RefNo = "135", Code = "PRK", Name = "North Korea" },
            new Country() { RefNo = "136", Code = "NOR", Name = "Norway" },
            new Country() { RefNo = "137", Code = "OMN", Name = "Oman" },
            new Country() { RefNo = "138", Code = "PAK", Name = "Pakistan" },
            new Country() { RefNo = "139", Code = "PLW", Name = "Palau" },
            new Country() { RefNo = "140", Code = "PSE", Name = "Palestine" },
            new Country() { RefNo = "141", Code = "PAN", Name = "Panama" },
            new Country() { RefNo = "142", Code = "PNG", Name = "Papua New Guinea" },
            new Country() { RefNo = "143", Code = "PRY", Name = "Paraguay" },
            new Country() { RefNo = "144", Code = "PER", Name = "Peru" },
            new Country() { RefNo = "145", Code = "PHL", Name = "Philippines" },
            new Country() { RefNo = "146", Code = "POL", Name = "Poland" },
            new Country() { RefNo = "147", Code = "PRT", Name = "Portugal" },
            new Country() { RefNo = "148", Code = "PRI", Name = "Puerto Rico" },
            new Country() { RefNo = "149", Code = "QAT", Name = "Qatar" },
            new Country() { RefNo = "150", Code = "MKD", Name = "Republic of North Macedonia" },
            new Country() { RefNo = "151", Code = "ROU", Name = "Romania" },
            new Country() { RefNo = "152", Code = "RUS", Name = "Russia" },
            new Country() { RefNo = "153", Code = "RWA", Name = "Rwanda" },
            new Country() { RefNo = "154", Code = "SPM", Name = "Saint Pierre and Miquelon" },
            new Country() { RefNo = "155", Code = "WSM", Name = "Samoa" },
            new Country() { RefNo = "156", Code = "SMR", Name = "San Marino" },
            new Country() { RefNo = "157", Code = "SAU", Name = "Saudi Arabia" },
            new Country() { RefNo = "158", Code = "SEN", Name = "Senegal" },
            new Country() { RefNo = "159", Code = "SRB", Name = "Serbia" },
            new Country() { RefNo = "160", Code = "SLE", Name = "Sierra Leone" },
            new Country() { RefNo = "161", Code = "SGP", Name = "Singapore" },
            new Country() { RefNo = "162", Code = "SXM", Name = "Sint Maarten" },
            new Country() { RefNo = "163", Code = "SVK", Name = "Slovakia" },
            new Country() { RefNo = "164", Code = "SVN", Name = "Slovenia" },
            new Country() { RefNo = "165", Code = "SLB", Name = "Solomon Islands" },
            new Country() { RefNo = "166", Code = "SOM", Name = "Somalia" },
            new Country() { RefNo = "167", Code = "ZAF", Name = "South Africa" },
            new Country() { RefNo = "168", Code = "KOR", Name = "South Korea" },
            new Country() { RefNo = "169", Code = "SSD", Name = "South Sudan" },
            new Country() { RefNo = "170", Code = "ESP", Name = "Spain" },
            new Country() { RefNo = "171", Code = "LKA", Name = "Sri Lanka" },
            new Country() { RefNo = "172", Code = "SDN", Name = "Sudan" },
            new Country() { RefNo = "173", Code = "SUR", Name = "Suriname" },
            new Country() { RefNo = "174", Code = "SWE", Name = "Sweden" },
            new Country() { RefNo = "175", Code = "CHE", Name = "Switzerland" },
            new Country() { RefNo = "176", Code = "SYR", Name = "Syrian Arab Republic" },
            new Country() { RefNo = "177", Code = "TWN", Name = "Taiwan" },
            new Country() { RefNo = "178", Code = "TJK", Name = "Tajikistan" },
            new Country() { RefNo = "179", Code = "TZA", Name = "Tanzania" },
            new Country() { RefNo = "180", Code = "THA", Name = "Thailand" },
            new Country() { RefNo = "181", Code = "TLS", Name = "Timor-Leste" },
            new Country() { RefNo = "182", Code = "TGO", Name = "Togo" },
            new Country() { RefNo = "183", Code = "TON", Name = "Tonga" },
            new Country() { RefNo = "184", Code = "TTO", Name = "Trinidad and Tobago" },
            new Country() { RefNo = "185", Code = "TUN", Name = "Tunisia" },
            new Country() { RefNo = "186", Code = "TUR", Name = "Turkey" },
            new Country() { RefNo = "187", Code = "TKM", Name = "Turkmenistan" },
            new Country() { RefNo = "188", Code = "TUV", Name = "Tuvalu" },
            new Country() { RefNo = "189", Code = "UGA", Name = "Uganda" },
            new Country() { RefNo = "190", Code = "UKR", Name = "Ukraine" },
            new Country() { RefNo = "191", Code = "ARE", Name = "United Arab Emirates" },
            new Country() { RefNo = "192", Code = "GBR", Name = "United Kingdom of Great Britain" },
            new Country() { RefNo = "193", Code = "USA", Name = "United States of America" },
            new Country() { RefNo = "194", Code = "URY", Name = "Uruguay" },
            new Country() { RefNo = "195", Code = "UZB", Name = "Uzbekistan" },
            new Country() { RefNo = "196", Code = "VEN", Name = "Venezuela" },
            new Country() { RefNo = "197", Code = "VNM", Name = "Vietnam" },
            new Country() { RefNo = "198", Code = "ESH", Name = "Western Sahara" },
            new Country() { RefNo = "199", Code = "YEM", Name = "Yemen" },
            new Country() { RefNo = "200", Code = "ZMB", Name = "Zambia" },
            new Country() { RefNo = "201", Code = "ZWE", Name = "Zimbabwe" },
        };

        public static List<Country> GetAll() => Countries;
    }
}
