namespace PortiaNet.Helper.MasterData
{
    public class Currency : MasterData
    {
        public string? Code { get; set; }

        private static readonly List<Currency> Currencies = new ()
        {
            new Currency { RefNo = "001", Code = "AED", Name = "UAE Dirham" },
            new Currency { RefNo = "002", Code = "AFN", Name = "Afghan Afghani" },
            new Currency { RefNo = "003", Code = "ALL", Name = "Albanian Lek" },
            new Currency { RefNo = "004", Code = "AMD", Name = "Armenian Dram" },
            new Currency { RefNo = "005", Code = "ANG", Name = "Netherlands Antilles Guilder" },
            new Currency { RefNo = "006", Code = "AOA", Name = "Angolan Kwanza" },
            new Currency { RefNo = "007", Code = "ARS", Name = "Argentine Peso" },
            new Currency { RefNo = "008", Code = "AUD", Name = "Australian Dollar" },
            new Currency { RefNo = "009", Code = "AWG", Name = "Aruban Florin" },
            new Currency { RefNo = "010", Code = "AZN", Name = "Azerbaijan Manat" },
            new Currency { RefNo = "011", Code = "BAM", Name = "Convertible Mark" },
            new Currency { RefNo = "012", Code = "BBD", Name = "Barbados Dollar" },
            new Currency { RefNo = "013", Code = "BDT", Name = "Bangladeshi Taka" },
            new Currency { RefNo = "014", Code = "BGN", Name = "Bulgarian Lev" },
            new Currency { RefNo = "015", Code = "BHD", Name = "Bahraini Dinar" },
            new Currency { RefNo = "016", Code = "BIF", Name = "Burundi Franc" },
            new Currency { RefNo = "017", Code = "BMD", Name = "Bermudian Dollar" },
            new Currency { RefNo = "018", Code = "BND", Name = "Brunei Dollar" },
            new Currency { RefNo = "019", Code = "BOB", Name = "Boliviano" },
            new Currency { RefNo = "020", Code = "BRL", Name = "Brazilian Real" },
            new Currency { RefNo = "021", Code = "BSD", Name = "Bahamian Dollar" },
            new Currency { RefNo = "022", Code = "BTN", Name = "Bhutanese Ngultrum" },
            new Currency { RefNo = "023", Code = "BWP", Name = "Pula" },
            new Currency { RefNo = "024", Code = "BYR", Name = "Belarusian Ruble" },
            new Currency { RefNo = "025", Code = "BZD", Name = "Belize Dollar" },
            new Currency { RefNo = "026", Code = "CAD", Name = "Canadian Dollar" },
            new Currency { RefNo = "027", Code = "CDF", Name = "Franc Congolais" },
            new Currency { RefNo = "028", Code = "CHF", Name = "Swiss Franc" },
            new Currency { RefNo = "029", Code = "CLP", Name = "Chilean Peso" },
            new Currency { RefNo = "030", Code = "CNY", Name = "Renminbi (Yuan)" },
            new Currency { RefNo = "031", Code = "COP", Name = "Colombian Peso" },
            new Currency { RefNo = "032", Code = "CRC", Name = "Costa Rican Colón" },
            new Currency { RefNo = "033", Code = "CSD", Name = "Serbian Dinar" },
            new Currency { RefNo = "034", Code = "CUP", Name = "Cuban Peso" },
            new Currency { RefNo = "035", Code = "CVE", Name = "Cape Verde Escudo" },
            new Currency { RefNo = "036", Code = "CZK", Name = "Czech Koruna" },
            new Currency { RefNo = "037", Code = "DJF", Name = "Djibouti Franc" },
            new Currency { RefNo = "038", Code = "DKK", Name = "Danish Kroner" },
            new Currency { RefNo = "039", Code = "DOP", Name = "Dominican Peso" },
            new Currency { RefNo = "040", Code = "DZD", Name = "Algerian Dinar" },
            new Currency { RefNo = "041", Code = "EEK", Name = "Estonian Kroon" },
            new Currency { RefNo = "042", Code = "EGP", Name = "Egyptian Pound" },
            new Currency { RefNo = "043", Code = "ERN", Name = "Nakfa" },
            new Currency { RefNo = "044", Code = "ETB", Name = "Ethiopian Birr" },
            new Currency { RefNo = "045", Code = "EUR", Name = "Euro" },
            new Currency { RefNo = "046", Code = "FJD", Name = "Fiji Dollar" },
            new Currency { RefNo = "047", Code = "FKP", Name = "Falkland Islands pound" },
            new Currency { RefNo = "048", Code = "FOK", Name = "Faroese króna" },
            new Currency { RefNo = "049", Code = "GBP", Name = "Pound Sterling" },
            new Currency { RefNo = "050", Code = "GEL", Name = "Lari" },
            new Currency { RefNo = "051", Code = "GHC", Name = "Cedi" },
            new Currency { RefNo = "052", Code = "GIP", Name = "Gibraltar Pound" },
            new Currency { RefNo = "053", Code = "GMD", Name = "Dalasi" },
            new Currency { RefNo = "054", Code = "GNF", Name = "Guinea Franc" },
            new Currency { RefNo = "055", Code = "GTQ", Name = "Quetzal" },
            new Currency { RefNo = "056", Code = "GWP", Name = "Guinea-Bissau Peso" },
            new Currency { RefNo = "057", Code = "GYD", Name = "Guyana Dollar" },
            new Currency { RefNo = "058", Code = "HKD", Name = "Hong Kong Dollar" },
            new Currency { RefNo = "059", Code = "HNL", Name = "Lempira" },
            new Currency { RefNo = "060", Code = "HRK", Name = "Croatian Kuna" },
            new Currency { RefNo = "061", Code = "HTG", Name = "Haitian Gourde" },
            new Currency { RefNo = "062", Code = "HUF", Name = "Forint" },
            new Currency { RefNo = "063", Code = "IDR", Name = "Rupiah" },
            new Currency { RefNo = "064", Code = "ILS", Name = "New Israeli Sheqel" },
            new Currency { RefNo = "065", Code = "INR", Name = "Indian Rupee" },
            new Currency { RefNo = "066", Code = "IQD", Name = "Iraqi Dinar" },
            new Currency { RefNo = "067", Code = "IRR", Name = "Iranian Rial" },
            new Currency { RefNo = "068", Code = "ISK", Name = "Iceland Krona" },
            new Currency { RefNo = "069", Code = "JMD", Name = "Jamaican Dollar" },
            new Currency { RefNo = "070", Code = "JOD", Name = "Jordanian Dinar" },
            new Currency { RefNo = "071", Code = "JPY", Name = "Yen" },
            new Currency { RefNo = "072", Code = "KES", Name = "Kenyan Shilling" },
            new Currency { RefNo = "073", Code = "KGS", Name = "Som" },
            new Currency { RefNo = "074", Code = "KHR", Name = "Cambodian Riel" },
            new Currency { RefNo = "075", Code = "KMF", Name = "Comoro Franc" },
            new Currency { RefNo = "076", Code = "KPW", Name = "North Korean Won" },
            new Currency { RefNo = "077", Code = "KRW", Name = "Won" },
            new Currency { RefNo = "078", Code = "KWD", Name = "Kuwaiti Dinar" },
            new Currency { RefNo = "079", Code = "KYD", Name = "Cayman Islands Dollar" },
            new Currency { RefNo = "080", Code = "KZT", Name = "Tenge" },
            new Currency { RefNo = "081", Code = "LAK", Name = "Kip" },
            new Currency { RefNo = "082", Code = "LBP", Name = "Lebanese Pound" },
            new Currency { RefNo = "083", Code = "LKR", Name = "Sri Lanka Rupee" },
            new Currency { RefNo = "084", Code = "LRD", Name = "Liberian Dollar" },
            new Currency { RefNo = "085", Code = "LSL", Name = "Loti (plural Maloti)" },
            new Currency { RefNo = "086", Code = "LTL", Name = "Euro replaced Lithuanian Litas" },
            new Currency { RefNo = "087", Code = "LYD", Name = "Lybian Dinar" },
            new Currency { RefNo = "088", Code = "MAD", Name = "Moroccan Dirham" },
            new Currency { RefNo = "089", Code = "MDL", Name = "Moldovan Leu" },
            new Currency { RefNo = "090", Code = "MGF", Name = "Malagasy Franc" },
            new Currency { RefNo = "091", Code = "MKD", Name = "Macedonian Denar" },
            new Currency { RefNo = "092", Code = "MMK", Name = "Burmese Kyat" },
            new Currency { RefNo = "093", Code = "MNT", Name = "Mongolia Tughrik (Tugrik, Tugrug, tögrög)" },
            new Currency { RefNo = "094", Code = "MOP", Name = "Macanese Pataca" },
            new Currency { RefNo = "095", Code = "MRO", Name = "Ouguiya" },
            new Currency { RefNo = "096", Code = "MTL", Name = "Maltese Lira" },
            new Currency { RefNo = "097", Code = "MUR", Name = "Mauritius Rupee" },
            new Currency { RefNo = "098", Code = "MVR", Name = "Rufiyaa" },
            new Currency { RefNo = "099", Code = "MWK", Name = "Kwacha" },
            new Currency { RefNo = "100", Code = "MXN", Name = "Mexican Peso" },
            new Currency { RefNo = "101", Code = "MYR", Name = "Malaysian Ringgit" },
            new Currency { RefNo = "102", Code = "MZM", Name = "Mozambican Metical" },
            new Currency { RefNo = "103", Code = "NAD", Name = "Namibia Dollar" },
            new Currency { RefNo = "104", Code = "NGN", Name = "Nigerian Naira" },
            new Currency { RefNo = "105", Code = "NIO", Name = "Nicaraguan Córdoba (córdoba oro)" },
            new Currency { RefNo = "106", Code = "NOK", Name = "Norwegian Krone" },
            new Currency { RefNo = "107", Code = "NPR", Name = "Nepalese Rupee" },
            new Currency { RefNo = "108", Code = "NZD", Name = "New Zealand Dollar" },
            new Currency { RefNo = "109", Code = "OMR", Name = "Omani Rial" },
            new Currency { RefNo = "110", Code = "PAB", Name = "Panamanian Balboa" },
            new Currency { RefNo = "111", Code = "PEN", Name = "Peruvian (Nuevo) Sol" },
            new Currency { RefNo = "112", Code = "PGK", Name = "Papua New Guinean Kina" },
            new Currency { RefNo = "113", Code = "PHP", Name = "Philippine Peso" },
            new Currency { RefNo = "114", Code = "PKR", Name = "Pakistan Rupee" },
            new Currency { RefNo = "115", Code = "PLN", Name = "Polish Zloty (złoty)" },
            new Currency { RefNo = "116", Code = "PYG", Name = "Paraguayan Guarani" },
            new Currency { RefNo = "117", Code = "QAR", Name = "Qatari Rial" },
            new Currency { RefNo = "118", Code = "ROL", Name = "Leu" },
            new Currency { RefNo = "119", Code = "RUR", Name = "Russian Ruble" },
            new Currency { RefNo = "120", Code = "RWF", Name = "Rwanda Franc" },
            new Currency { RefNo = "121", Code = "SAR", Name = "Saudi Riyal" },
            new Currency { RefNo = "122", Code = "SBD", Name = "Solomon Islands Dollar" },
            new Currency { RefNo = "123", Code = "SCR", Name = "Seychelles Rupee" },
            new Currency { RefNo = "124", Code = "SDD", Name = "Sudanese Dinar" },
            new Currency { RefNo = "125", Code = "SEK", Name = "Swedish Krona" },
            new Currency { RefNo = "126", Code = "SGD", Name = "Singapore Dollar" },
            new Currency { RefNo = "127", Code = "SHP", Name = "Saint Helena Pound" },
            new Currency { RefNo = "128", Code = "SLL", Name = "Leone" },
            new Currency { RefNo = "129", Code = "SOS", Name = "Somali Shilling" },
            new Currency { RefNo = "130", Code = "SRG", Name = "Suriname Guilder" },
            new Currency { RefNo = "131", Code = "SSP", Name = "South Sudanese pound" },
            new Currency { RefNo = "132", Code = "STD", Name = "Dobra" },
            new Currency { RefNo = "133", Code = "SVC", Name = "Salvadoran Colón" },
            new Currency { RefNo = "134", Code = "SYP", Name = "Syrian Pound" },
            new Currency { RefNo = "135", Code = "SZL", Name = "Lilangeni" },
            new Currency { RefNo = "136", Code = "THB", Name = "Thai Baht" },
            new Currency { RefNo = "137", Code = "TJS", Name = "Somoni" },
            new Currency { RefNo = "138", Code = "TMM", Name = "Manat" },
            new Currency { RefNo = "139", Code = "TND", Name = "Tunisian Dinar" },
            new Currency { RefNo = "140", Code = "TOP", Name = "Paʻanga" },
            new Currency { RefNo = "141", Code = "TRY", Name = "Yeni Türk Liras (YTL)" },
            new Currency { RefNo = "142", Code = "TTD", Name = "Trinidad and Tobago Dollar" },
            new Currency { RefNo = "143", Code = "TWD", Name = "New Taiwan Dollar" },
            new Currency { RefNo = "144", Code = "TZS", Name = "Tanzanian Shilling" },
            new Currency { RefNo = "145", Code = "UAH", Name = "Ukrainian Hryvnia" },
            new Currency { RefNo = "146", Code = "UGX", Name = "Uganda Shilling" },
            new Currency { RefNo = "147", Code = "USD", Name = "US Dollar" },
            new Currency { RefNo = "148", Code = "USS", Name = "US Dollar r (Same day)" },
            new Currency { RefNo = "149", Code = "UYU", Name = "Uruguayan Peso" },
            new Currency { RefNo = "150", Code = "UZS", Name = "Uzbekistan Sum" },
            new Currency { RefNo = "151", Code = "VEF", Name = "Venezuelan Bolívar" },
            new Currency { RefNo = "152", Code = "VND", Name = "Vietnamese Dong" },
            new Currency { RefNo = "153", Code = "VUV", Name = "Vanuatu Vatu" },
            new Currency { RefNo = "154", Code = "WST", Name = "Tala" },
            new Currency { RefNo = "155", Code = "XAF", Name = "CFA Franc BEAC" },
            new Currency { RefNo = "156", Code = "XCD", Name = "East Caribbean Dollar" },
            new Currency { RefNo = "157", Code = "XOF", Name = "CFA Franc BCEAO" },
            new Currency { RefNo = "158", Code = "XPF", Name = "CFP Franc" },
            new Currency { RefNo = "159", Code = "YER", Name = "Yemeni Rial" },
            new Currency { RefNo = "160", Code = "ZAR", Name = "Rand" },
            new Currency { RefNo = "161", Code = "ZMW", Name = "Zambian Kwacha" },
            new Currency { RefNo = "162", Code = "ZWD", Name = "Zimbabwe Dollar" }
        };

        public static List<Currency> GetAll() => Currencies;
    }
}
