namespace PortiaNet.Helper.MasterData
{
    public class Language : MasterData
    {
        private static List<Language> Languages => new()
        {
            new Language { RefNo = "001", Name = "Amharic (Ethiopia)" },
            new Language { RefNo = "002", Name = "Amoy" },
            new Language { RefNo = "003", Name = "Arabic" },
            new Language { RefNo = "004", Name = "Armenian" },
            new Language { RefNo = "005", Name = "Azerbaijani" },
            new Language { RefNo = "006", Name = "Belarusian" },
            new Language { RefNo = "007", Name = "Bengali" },
            new Language { RefNo = "008", Name = "Bikol" },
            new Language { RefNo = "009", Name = "Bosnian" },
            new Language { RefNo = "010", Name = "Brazilian Portuguese" },
            new Language { RefNo = "011", Name = "Bulgarian" },
            new Language { RefNo = "012", Name = "Burmese" },
            new Language { RefNo = "013", Name = "Canadian French" },
            new Language { RefNo = "014", Name = "Cantonese" },
            new Language { RefNo = "015", Name = "Catalan" },
            new Language { RefNo = "016", Name = "Cebuano" },
            new Language { RefNo = "017", Name = "Cham" },
            new Language { RefNo = "018", Name = "Chamorro (Guam)" },
            new Language { RefNo = "019", Name = "Chinese" },
            new Language { RefNo = "020", Name = "Chinese–Simplified" },
            new Language { RefNo = "021", Name = "Chinese–Traditional" },
            new Language { RefNo = "022", Name = "Chiu Chow" },
            new Language { RefNo = "023", Name = "Chow Jo" },
            new Language { RefNo = "024", Name = "Croatian" },
            new Language { RefNo = "025", Name = "Czech" },
            new Language { RefNo = "026", Name = "Danish" },
            new Language { RefNo = "027", Name = "Dari" },
            new Language { RefNo = "028", Name = "Dinka (Sudan)" },
            new Language { RefNo = "029", Name = "Dutch" },
            new Language { RefNo = "030", Name = "English" },
            new Language { RefNo = "031", Name = "Estonian" },
            new Language { RefNo = "032", Name = "Faroese" },
            new Language { RefNo = "033", Name = "Fijian" },
            new Language { RefNo = "034", Name = "Finnish" },
            new Language { RefNo = "035", Name = "Flemish" },
            new Language { RefNo = "036", Name = "French" },
            new Language { RefNo = "037", Name = "French Creole" },
            new Language { RefNo = "038", Name = "Fukienese" },
            new Language { RefNo = "039", Name = "Georgian" },
            new Language { RefNo = "040", Name = "German" },
            new Language { RefNo = "041", Name = "Greek" },
            new Language { RefNo = "042", Name = "Gujarati (India)" },
            new Language { RefNo = "043", Name = "Hainanese" },
            new Language { RefNo = "044", Name = "Haitian Creole" },
            new Language { RefNo = "045", Name = "Hakka (China)" },
            new Language { RefNo = "046", Name = "Hebrew" },
            new Language { RefNo = "047", Name = "Hindi" },
            new Language { RefNo = "048", Name = "Hmong" },
            new Language { RefNo = "049", Name = "Hungarian" },
            new Language { RefNo = "050", Name = "Ibo (Nigeria)" },
            new Language { RefNo = "051", Name = "Icelandic" },
            new Language { RefNo = "052", Name = "Ilocano" },
            new Language { RefNo = "053", Name = "Ilongo" },
            new Language { RefNo = "054", Name = "Indonesian" },
            new Language { RefNo = "055", Name = "Italian" },
            new Language { RefNo = "056", Name = "Japanese" },
            new Language { RefNo = "057", Name = "Kazakh" },
            new Language { RefNo = "058", Name = "Khmer (Cambodia)" },
            new Language { RefNo = "059", Name = "Kinyarwanda" },
            new Language { RefNo = "060", Name = "Kirundi" },
            new Language { RefNo = "061", Name = "Kmhmu (Laos)" },
            new Language { RefNo = "062", Name = "Korean" },
            new Language { RefNo = "063", Name = "Kurdish" },
            new Language { RefNo = "064", Name = "Laotian" },
            new Language { RefNo = "065", Name = "Latvian" },
            new Language { RefNo = "066", Name = "Lithuanian" },
            new Language { RefNo = "067", Name = "Macedonian" },
            new Language { RefNo = "068", Name = "Malay" },
            new Language { RefNo = "069", Name = "Malayalam" },
            new Language { RefNo = "070", Name = "Mandarin" },
            new Language { RefNo = "071", Name = "Mandinka" },
            new Language { RefNo = "072", Name = "Marathi (India" },
            new Language { RefNo = "073", Name = "Marshallese" },
            new Language { RefNo = "074", Name = "Mien" },
            new Language { RefNo = "075", Name = "Mongolian" },
            new Language { RefNo = "076", Name = "Navajo" },
            new Language { RefNo = "077", Name = "Nepali" },
            new Language { RefNo = "078", Name = "Norwegian" },
            new Language { RefNo = "079", Name = "Nuer (Nilo-Saharan)" },
            new Language { RefNo = "080", Name = "Oromo (Ethiopia)" },
            new Language { RefNo = "081", Name = "Palauan" },
            new Language { RefNo = "082", Name = "Pampangan" },
            new Language { RefNo = "083", Name = "Pangasinan" },
            new Language { RefNo = "084", Name = "Pashtu" },
            new Language { RefNo = "085", Name = "Persian" },
            new Language { RefNo = "086", Name = "Polish" },
            new Language { RefNo = "087", Name = "Portuguese" },
            new Language { RefNo = "088", Name = "Punjabi" },
            new Language { RefNo = "089", Name = "Quechua" },
            new Language { RefNo = "090", Name = "Romanian" },
            new Language { RefNo = "091", Name = "Russian" },
            new Language { RefNo = "092", Name = "Samoan" },
            new Language { RefNo = "093", Name = "Serbian" },
            new Language { RefNo = "094", Name = "Shanghainese" },
            new Language { RefNo = "095", Name = "Sherpa" },
            new Language { RefNo = "096", Name = "Shona (Zimbabwe)" },
            new Language { RefNo = "097", Name = "Slovak" },
            new Language { RefNo = "098", Name = "Slovenian" },
            new Language { RefNo = "099", Name = "Somali" },
            new Language { RefNo = "100", Name = "Spanish" },
            new Language { RefNo = "101", Name = "Spanish" },
            new Language { RefNo = "102", Name = "Swahili" },
            new Language { RefNo = "103", Name = "Swedish" },
            new Language { RefNo = "104", Name = "Tagalog" },
            new Language { RefNo = "105", Name = "Taishanese" },
            new Language { RefNo = "106", Name = "Taiwanese" },
            new Language { RefNo = "107", Name = "Tamil" },
            new Language { RefNo = "108", Name = "Thai" },
            new Language { RefNo = "109", Name = "Tibetan" },
            new Language { RefNo = "110", Name = "Tigrigna (Ethiopia)" },
            new Language { RefNo = "111", Name = "Tongan" },
            new Language { RefNo = "112", Name = "Trukese (Micronesia)" },
            new Language { RefNo = "113", Name = "Turkish" },
            new Language { RefNo = "114", Name = "Turkmen" },
            new Language { RefNo = "115", Name = "UK English" },
            new Language { RefNo = "116", Name = "Ukrainian" },
            new Language { RefNo = "117", Name = "Urdu (Pakistan)" },
            new Language { RefNo = "118", Name = "Uzbek" },
            new Language { RefNo = "119", Name = "Vietnamese" },
            new Language { RefNo = "120", Name = "Visayan" },
            new Language { RefNo = "121", Name = "Wolof" },
            new Language { RefNo = "122", Name = "Xhosa" },
            new Language { RefNo = "123", Name = "Yoruba" },
            new Language { RefNo = "124", Name = "Zulu" }
        };

        public static List<Language> GetAll() => Languages;
    }
}
