namespace PortiaNet.Helper.MasterData
{
    public class TimeZone : MasterData
    {
        public string RegionName { get; set; } = string.Empty;

        public string Value { get; set; } = string.Empty;


        private static List<TimeZone> _items = new() 
        {
            new TimeZone { RefNo = "001", Value = "-12:00", Name = "(UTC-12:00) International Date Line West", RegionName = "Etc/GMT+12"},
            new TimeZone { RefNo = "002", Value = "-11:00", Name = "(UTC-11:00) Coordinated Universal Time-11", RegionName = "Etc/GMT+11"},
            new TimeZone { RefNo = "003", Value = "-10:00", Name = "(UTC-10:00) Hawaii", RegionName = "Pacific/Honolulu"},
            new TimeZone { RefNo = "004", Value = "-09:00", Name = "(UTC-09:00) Alaska", RegionName = "America/Anchorage"},
            new TimeZone { RefNo = "005", Value = "-08:00", Name = "(UTC-08:00) Baja California", RegionName = "America/Santa_Isabel"},
            new TimeZone { RefNo = "006", Value = "-08:00", Name = "(UTC-08:00) Pacific Time (US and Canada)", RegionName = "America/Los_Angeles"},
            new TimeZone { RefNo = "007", Value = "-07:00", Name = "(UTC-07:00) Chihuahua, La Paz, Mazatlan", RegionName = "America/Chihuahua"},
            new TimeZone { RefNo = "008", Value = "-07:00", Name = "(UTC-07:00) Arizona", RegionName = "America/Phoenix"},
            new TimeZone { RefNo = "009", Value = "-07:00", Name = "(UTC-07:00) Mountain Time (US and Canada)", RegionName = "America/Denver"},
            new TimeZone { RefNo = "010", Value = "-06:00", Name = "(UTC-06:00) Central America", RegionName = "America/Guatemala"},
            new TimeZone { RefNo = "011", Value = "-06:00", Name = "(UTC-06:00) Central Time (US and Canada)", RegionName = "America/Chicago"},
            new TimeZone { RefNo = "012", Value = "-06:00", Name = "(UTC-06:00) Saskatchewan", RegionName = "America/Regina"},
            new TimeZone { RefNo = "013", Value = "-06:00", Name = "(UTC-06:00) Guadalajara, Mexico City, Monterey", RegionName = "America/Mexico_City"},
            new TimeZone { RefNo = "014", Value = "-05:00", Name = "(UTC-05:00) Bogota, Lima, Quito", RegionName = "America/Bogota"},
            new TimeZone { RefNo = "015", Value = "-05:00", Name = "(UTC-05:00) Indiana (East)", RegionName = "America/Indiana/Indianapolis"},
            new TimeZone { RefNo = "016", Value = "-05:00", Name = "(UTC-05:00) Eastern Time (US and Canada)", RegionName = "America/New_York"},
            new TimeZone { RefNo = "017", Value = "-04:30", Name = "(UTC-04:30) Caracas", RegionName = "America/Caracas"},
            new TimeZone { RefNo = "018", Value = "-04:00", Name = "(UTC-04:00) Atlantic Time (Canada)", RegionName = "America/Halifax"},
            new TimeZone { RefNo = "019", Value = "-04:00", Name = "(UTC-04:00) Asuncion", RegionName = "America/Asuncion"},
            new TimeZone { RefNo = "020", Value = "-04:00", Name = "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan", RegionName = "America/La_Paz"},
            new TimeZone { RefNo = "021", Value = "-04:00", Name = "(UTC-04:00) Cuiaba", RegionName = "America/Cuiaba"},
            new TimeZone { RefNo = "022", Value = "-04:00", Name = "(UTC-04:00) Santiago", RegionName = "America/Santiago"},
            new TimeZone { RefNo = "023", Value = "-03:30", Name = "(UTC-03:30) Newfoundland", RegionName = "America/St_Johns"},
            new TimeZone { RefNo = "024", Value = "-03:00", Name = "(UTC-03:00) Brasilia", RegionName = "America/Sao_Paulo"},
            new TimeZone { RefNo = "025", Value = "-03:00", Name = "(UTC-03:00) Greenland", RegionName = "America/Godthab"},
            new TimeZone { RefNo = "026", Value = "-03:00", Name = "(UTC-03:00) Cayenne, Fortaleza", RegionName = "America/Cayenne"},
            new TimeZone { RefNo = "027", Value = "-03:00", Name = "(UTC-03:00) Buenos Aires", RegionName = "America/Argentina/Buenos_Aires"},
            new TimeZone { RefNo = "028", Value = "-03:00", Name = "(UTC-03:00) Montevideo", RegionName = "America/Montevideo"},
            new TimeZone { RefNo = "029", Value = "-02:00", Name = "(UTC-02:00) Coordinated Universal Time-2", RegionName = "Etc/GMT+2"},
            new TimeZone { RefNo = "030", Value = "-01:00", Name = "(UTC-01:00) Cape Verde", RegionName = "Atlantic/Cape_Verde"},
            new TimeZone { RefNo = "031", Value = "-01:00", Name = "(UTC-01:00) Azores", RegionName = "Atlantic/Azores"},
            new TimeZone { RefNo = "032", Value = "+00:00", Name = "(UTC+00:00) Casablanca", RegionName = "Africa/Casablanca"},
            new TimeZone { RefNo = "033", Value = "+00:00", Name = "(UTC+00:00) Monrovia, Reykjavik", RegionName = "Atlantic/Reykjavik"},
            new TimeZone { RefNo = "034", Value = "+00:00", Name = "(UTC+00:00) Dublin, Edinburgh, Lisbon, London", RegionName = "Europe/London"},
            new TimeZone { RefNo = "035", Value = "+00:00", Name = "(UTC+00:00) Coordinated Universal Time", RegionName = "Etc/GMT"},
            new TimeZone { RefNo = "036", Value = "+01:00", Name = "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna", RegionName = "Europe/Berlin"},
            new TimeZone { RefNo = "037", Value = "+01:00", Name = "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris", RegionName = "Europe/Paris"},
            new TimeZone { RefNo = "038", Value = "+01:00", Name = "(UTC+01:00) West Central Africa", RegionName = "Africa/Lagos"},
            new TimeZone { RefNo = "039", Value = "+01:00", Name = "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague", RegionName = "Europe/Budapest"},
            new TimeZone { RefNo = "040", Value = "+01:00", Name = "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb", RegionName = "Europe/Warsaw"},
            new TimeZone { RefNo = "041", Value = "+01:00", Name = "(UTC+01:00) Windhoek", RegionName = "Africa/Windhoek"},
            new TimeZone { RefNo = "042", Value = "+02:00", Name = "(UTC+02:00) Athens, Bucharest, Istanbul", RegionName = "Europe/Istanbul"},
            new TimeZone { RefNo = "043", Value = "+02:00", Name = "(UTC+02:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius", RegionName = "Europe/Kiev"},
            new TimeZone { RefNo = "044", Value = "+02:00", Name = "(UTC+02:00) Cairo", RegionName = "Africa/Cairo"},
            new TimeZone { RefNo = "045", Value = "+02:00", Name = "(UTC+02:00) Damascus", RegionName = "Asia/Damascus"},
            new TimeZone { RefNo = "046", Value = "+02:00", Name = "(UTC+02:00) Amman", RegionName = "Asia/Amman"},
            new TimeZone { RefNo = "047", Value = "+02:00", Name = "(UTC+02:00) Harare, Pretoria", RegionName = "Africa/Johannesburg"},
            new TimeZone { RefNo = "048", Value = "+02:00", Name = "(UTC+02:00) Jerusalem", RegionName = "Asia/Jerusalem"},
            new TimeZone { RefNo = "049", Value = "+02:00", Name = "(UTC+02:00) Beirut", RegionName = "Asia/Beirut"},
            new TimeZone { RefNo = "050", Value = "+03:00", Name = "(UTC+03:00) Baghdad", RegionName = "Asia/Baghdad"},
            new TimeZone { RefNo = "051", Value = "+03:00", Name = "(UTC+03:00) Minsk", RegionName = "Europe/Minsk"},
            new TimeZone { RefNo = "052", Value = "+03:00", Name = "(UTC+03:00) Kuwait, Riyadh", RegionName = "Asia/Riyadh"},
            new TimeZone { RefNo = "053", Value = "+03:00", Name = "(UTC+03:00) Nairobi", RegionName = "Africa/Nairobi"},
            new TimeZone { RefNo = "054", Value = "+03:30", Name = "(UTC+03:30) Tehran", RegionName = "Asia/Tehran"},
            new TimeZone { RefNo = "055", Value = "+04:00", Name = "(UTC+04:00) Moscow, St. Petersburg, Volgograd", RegionName = "Europe/Moscow"},
            new TimeZone { RefNo = "056", Value = "+04:00", Name = "(UTC+04:00) Tbilisi", RegionName = "Asia/Tbilisi"},
            new TimeZone { RefNo = "057", Value = "+04:00", Name = "(UTC+04:00) Yerevan", RegionName = "Asia/Yerevan"},
            new TimeZone { RefNo = "058", Value = "+04:00", Name = "(UTC+04:00) Abu Dhabi, Muscat", RegionName = "Asia/Dubai"},
            new TimeZone { RefNo = "059", Value = "+04:00", Name = "(UTC+04:00) Baku", RegionName = "Asia/Baku"},
            new TimeZone { RefNo = "060", Value = "+04:00", Name = "(UTC+04:00) Port Louis", RegionName = "Indian/Mauritius"},
            new TimeZone { RefNo = "061", Value = "+04:30", Name = "(UTC+04:30) Kabul", RegionName = "Asia/Kabul"},
            new TimeZone { RefNo = "062", Value = "+05:00", Name = "(UTC+05:00) Tashkent", RegionName = "Asia/Tashkent"},
            new TimeZone { RefNo = "063", Value = "+05:00", Name = "(UTC+05:00) Islamabad, Karachi", RegionName = "Asia/Karachi"},
            new TimeZone { RefNo = "064", Value = "+05:30", Name = "(UTC+05:30) Sri Jayewardenepura Kotte", RegionName = "Asia/Colombo"},
            new TimeZone { RefNo = "065", Value = "+05:30", Name = "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi", RegionName = "Asia/Kolkata"},
            new TimeZone { RefNo = "066", Value = "+05:45", Name = "(UTC+05:45) Kathmandu", RegionName = "Asia/Kathmandu"},
            new TimeZone { RefNo = "067", Value = "+06:00", Name = "(UTC+06:00) Astana", RegionName = "Asia/Almaty"},
            new TimeZone { RefNo = "068", Value = "+06:00", Name = "(UTC+06:00) Dhaka", RegionName = "Asia/Dhaka"},
            new TimeZone { RefNo = "069", Value = "+06:00", Name = "(UTC+06:00) Yekaterinburg", RegionName = "Asia/Yekaterinburg"},
            new TimeZone { RefNo = "070", Value = "+06:30", Name = "(UTC+06:30) Yangon", RegionName = "Asia/Yangon"},
            new TimeZone { RefNo = "071", Value = "+07:00", Name = "(UTC+07:00) Bangkok, Hanoi, Jakarta", RegionName = "Asia/Bangkok"},
            new TimeZone { RefNo = "072", Value = "+07:00", Name = "(UTC+07:00) Novosibirsk", RegionName = "Asia/Novosibirsk"},
            new TimeZone { RefNo = "073", Value = "+08:00", Name = "(UTC+08:00) Krasnoyarsk", RegionName = "Asia/Krasnoyarsk"},
            new TimeZone { RefNo = "074", Value = "+08:00", Name = "(UTC+08:00) Ulaanbaatar", RegionName = "Asia/Ulaanbaatar"},
            new TimeZone { RefNo = "075", Value = "+08:00", Name = "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi", RegionName = "Asia/Shanghai"},
            new TimeZone { RefNo = "076", Value = "+08:00", Name = "(UTC+08:00) Perth", RegionName = "Australia/Perth"},
            new TimeZone { RefNo = "077", Value = "+08:00", Name = "(UTC+08:00) Kuala Lumpur, Singapore", RegionName = "Asia/Singapore"},
            new TimeZone { RefNo = "078", Value = "+08:00", Name = "(UTC+08:00) Taipei", RegionName = "Asia/Taipei"},
            new TimeZone { RefNo = "079", Value = "+09:00", Name = "(UTC+09:00) Irkutsk", RegionName = "Asia/Irkutsk"},
            new TimeZone { RefNo = "080", Value = "+09:00", Name = "(UTC+09:00) Seoul", RegionName = "Asia/Seoul"},
            new TimeZone { RefNo = "081", Value = "+09:00", Name = "(UTC+09:00) Osaka, Sapporo, Tokyo", RegionName = "Asia/Tokyo"},
            new TimeZone { RefNo = "082", Value = "+09:30", Name = "(UTC+09:30) Darwin", RegionName = "Australia/Darwin"},
            new TimeZone { RefNo = "083", Value = "+09:30", Name = "(UTC+09:30) Adelaide", RegionName = "Australia/Adelaide"},
            new TimeZone { RefNo = "084", Value = "+10:00", Name = "(UTC+10:00) Hobart", RegionName = "Australia/Hobart"},
            new TimeZone { RefNo = "085", Value = "+10:00", Name = "(UTC+10:00) Yakutsk", RegionName = "Asia/Yakutsk"},
            new TimeZone { RefNo = "086", Value = "+10:00", Name = "(UTC+10:00) Brisbane", RegionName = "Australia/Brisbane"},
            new TimeZone { RefNo = "087", Value = "+10:00", Name = "(UTC+10:00) Guam, Port Moresby", RegionName = "Pacific/Port_Moresby"},
            new TimeZone { RefNo = "088", Value = "+10:00", Name = "(UTC+10:00) Canberra, Melbourne, Sydney", RegionName = "Australia/Sydney"},
            new TimeZone { RefNo = "089", Value = "+11:00", Name = "(UTC+11:00) Vladivostok", RegionName = "Asia/Vladivostok"},
            new TimeZone { RefNo = "090", Value = "+11:00", Name = "(UTC+11:00) Solomon Islands, New Caledonia", RegionName = "Pacific/Guadalcanal"},
            new TimeZone { RefNo = "091", Value = "+12:00", Name = "(UTC+12:00) Coordinated Universal Time+12", RegionName = "Etc/GMT-12"},
            new TimeZone { RefNo = "092", Value = "+12:00", Name = "(UTC+12:00) Fiji, Marshall Islands", RegionName = "Pacific/Fiji"},
            new TimeZone { RefNo = "093", Value = "+12:00", Name = "(UTC+12:00) Magadan", RegionName = "Asia/Magadan"},
            new TimeZone { RefNo = "094", Value = "+12:00", Name = "(UTC+12:00) Auckland, Wellington", RegionName = "Pacific/Auckland"},
            new TimeZone { RefNo = "095", Value = "+13:00", Name = "(UTC+13:00) Nuku'alofa", RegionName = "Pacific/Tongatapu"},
            new TimeZone { RefNo = "096", Value = "+13:00", Name = "(UTC+13:00) Samoa", RegionName = "Pacific/Apia" }
        };

        public static List<TimeZone> GetAll() => _items;
    }
}
