<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>PortiaNet .Net Helper</Title>
    <Authors>Amin Esmaeily</Authors>
    <Description>PortiaNet.Helper contains some helpful methods and functions to speedup the work and reduce duplicate works.</Description>
    <PackageProjectUrl>https://github.com/PortiaNet/Helper</PackageProjectUrl>
    <PackageIcon>settings.png</PackageIcon>
    <RepositoryUrl>https://github.com/PortiaNet/Helper</RepositoryUrl>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageTags>.Net; Helper; Tools; Class Library; AI; Vision; OCR; Card Recognition; Business Card; Credit Card; ML; ONNX; EF; EF Core; Encryption; Decryption; Cypher; AES;</PackageTags>
    <Version>2.1.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\readme.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\settings.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.5" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.22.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Ai\Models\ocr.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Ai\Models\cait_m48_448_Opset18.onnx.crdownload">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
